import Head from 'next/head';
import Avatar from "../components/Avatar";
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid";
import Image from "next/image";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
  if(!term) return;

  router.push(`/search?term=${term}`);

  }

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <header className="flex w-full p-5 justify-between text-sm text-gray-700">
    <div className="flex space-x-4 items-center">
    <p className="link">About</p>
    <p className="link">Store</p>
    </div>
    
    <div className="flex space-x-4 items-center">
    <p className="link">Gmail</p>
    <p className="link">Images</p>
    <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
    <Avatar url="https://www.w3schools.com/w3images/avatar6.png" />
    </div>
    </header>
    <form className="flex flex-grow flex-col items-center mt-44 w-4/5">
    <Image
    src="https://cdn.worldvectorlogo.com/logos/google-2015.svg"
    alt="My Google Logo"
    height={100}
    width={300} />

    <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md
    rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
    <SearchIcon className="h-5 mr-3 text-gray-500" />
    <input type="text"
    ref={searchInputRef}
    placeholder="Search Google or type a Url"
    className="flex-grow focus:outline-none" />
    <MicrophoneIcon className="h-5" />
     </div>
     
     <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8
     sm:space-y-1 sm:flex-row sm:space-x-8">
     <button onClick={search} className="btn">Google Search</button>
     <button onClick={search} className="btn">I&apos;m Feeling Lucky</button>
     </div>
    </form>
    <Footer />
    </div>
  )
}
